include:
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/pre-commit@mr/boris/first-attempts
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/tox@mr/boris/first-attempts
    inputs:
      tox-section: py311-cov
      stage: test

stages:
  - check
  - test
