name: Continuous Integration
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                # Add windows-latest once the rlimit problem is fixed
                # (T608-018).
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get e3-testsuite
              uses: actions/checkout@v2
              with:
                path: e3-testsuite

            # Clone e3-core just near e3-testsuite so that our Mypy
            # configuration helps Mypy to find type hints for e3-core.
            - name: Get e3-core
              uses: actions/checkout@v2
              with:
                repository: AdaCore/e3-core
                path: e3-core

            - uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            - name: Setup testing tools
              run: |
                pip install --upgrade pip
                pip install tox
                pip install mypy==0.790

            - name: Type check with Mypy
              run: |
                cd e3-testsuite
                mypy

            # Run the testsuite and style checks
            - name: Run the testsuite & style checks
              run: |
                cd e3-testsuite
                tox -e py-ci-cov-codecov,checkstyle,security
